demo5/blueprints/user1.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session, flash
from exts import mail, db
from flask_mail import Message
from models import EmailCpatcharModel, UserModel, QuestionModel, AnswerModel
import string
import random
from datetime import datetime
from blueprints.forms import RegisterForm, LoginForm, QuestionForm, AnswerForm, ChangeForm
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy import or_
from logintest import login_manager
from flask_login import login_required, login_user, logout_user, current_user
from .check import *

bp = Blueprint("user1", __name__, url_prefix="/")

login_manager.session_protection = 'basic'
login_manager.login_view = 'user1.login'
login_manager.login_message = u"请先登录。"


@bp.route("/")
def index():
    questions = QuestionModel.query.order_by(QuestionModel.create_time.desc()).all()
    return render_template("index.html", questions=questions)


@bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password, password):
                login_user(user)  # 关键就是 login_user(curr_user) 这句代码，之前要构建 User 对象，并指定 id。
                # session['user_id'] = user.id
                # session['username'] = user.username
                return redirect("/")
            else:
                flash("邮箱和密码不匹配!")
                return redirect(url_for("user1.login"))
        else:
            flash("邮箱或者密码格式不对!")
            return redirect(url_for("user1.login"))


@bp.route('/logout')
def logout():
    # 退出
    logout_user()
    return redirect(url_for("user1.login"))


@bp.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            hash_password = generate_password_hash(password)

            user = UserModel(username=username, email=email, password=hash_password)

            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user1.login"))
        else:
            print(form.errors)
            flash(form.errors)

            return redirect(url_for("user1.register"))


@bp.route("/captcha", methods=['POST'])
def get_captcha():
    # 默认get方法args   POST
    email = request.form.get("email")
    letters = string.ascii_letters + string.digits
    captcha = "".join(random.sample(letters, 4))
    email1 = UserModel.query.filter_by(email=email).first()
    if check_email_url(email=email):
        return jsonify({"code": 5002, "message": "请输入正确的邮箱"})
    if email1:
        return jsonify({"code": 5001, "message": "邮箱已经注册，请切换邮箱注册"})
    elif email:
        message = Message(
            subject="邮箱测试",
            recipients=[email],
            body=f"您的注册码是：{captcha}.不要告诉任何人"
        )
        # print(captcha)
        mail.send(message)
        captcha_model = EmailCpatcharModel.query.filter_by(email=email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.create_time = datetime.now()
            db.session.commit()
        else:
            captcha_model = EmailCpatcharModel(email=email, captcha=captcha)
            db.session.add(captcha_model)
            db.session.commit()

        return jsonify({"code": 200, "message": "验证码发生成功"})
    else:
        return jsonify({"code": 400, "message": "请先输入邮箱"})


@bp.route("/public", methods=['GET', 'POST'])
@login_required
def public_question():
    if request.method == 'GET':
        return render_template("public_question.html")
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content, author=current_user)
            db.session.add(question)
            db.session.commit()
            return redirect('/')
        else:
            flash("标题或内容格式错误！")
            return redirect(url_for("user1.public_question"))


@bp.route("/question/<int:question_id>")
def question_detail(question_id):
    question = QuestionModel.query.get(question_id)
    return render_template("detail.html", question=question)


@bp.route("/answer/<int:question_id>", methods=['POST'])
@login_required
def answer(question_id):
    form = AnswerForm(request.form)
    if form.validate():
        content = form.content.data
        answer_model = AnswerModel(content=content, author=current_user, question_id=question_id)
        db.session.add(answer_model)
        db.session.commit()
        return redirect(url_for("user1.question_detail", question_id=question_id))
    else:
        flash("表单验证失败")
        return redirect(url_for("user1.question_detail", question_id=question_id))


@bp.route('/search')
def search():
    q = request.args.get("q")
    questions = QuestionModel.query.filter(or_(QuestionModel.title.contains(q), QuestionModel.content.contains(q))) \
        .order_by(QuestionModel.create_time.desc())
    return render_template("index.html", questions=questions)


@bp.route('/core', methods=['GET', 'POST'])
@login_required
def core():
    return render_template("core.html")


@bp.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    if request.method == 'GET':
        return render_template("change_password.html")
    else:
        form = ChangeForm(request.form)
        if form.validate():
            password1 = UserModel.query.filter_by(email=current_user.email).first()
            change_password1 = form.change_password.data
            change_password2 = form.change_password1.data
            hash_password = generate_password_hash(change_password1)

            if check_password_hash(password1.password, change_password1):
                flash("不能跟原始密码一样")
                return redirect(url_for("user1.change_password"))
            else:
                print(change_password1, change_password2)
                user = UserModel.query.filter(UserModel.email == current_user.email).\
                    update({UserModel.password: hash_password})

                # suer = UserModel.query.filter_by(email=current_user.email).first()
                # suer.password = hash_password
                db.session.commit()

                return redirect(url_for("user1.index"))
        else:
            print(form.change_password1.errors)
            flash(form.errors)
            return redirect(url_for("user1.change_password"))

demo5/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%} {% endblock%}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='uploads/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css')}}">
    <script src="{{ url_for('static', filename='jquery/jquery.3.6.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
    {%block head%}

    {% endblock%}
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">练习1111</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">首页</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user1.public_question')}}">发布问答</a>
                </li>
                <li class="nav-item ml-2">
                    <form class="form-inline my-2 my-lg-0" method="get" action="{{ url_for('user1.search')}}">
                        <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search"
                               name="q">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                    </form>
                </li>
            </ul>

            {% if current_user.username %}

            <div class="dropdown">
                <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                        aria-expanded="false">
                    {{ current_user.username}}
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item nav-link " href=" {{ url_for('user1.core')}}">个人中心</a>
                    <a class="dropdown-item nav-link" href="{{ url_for('user1.change_password')}}">修改密码</a>
                </div>
            </div>
            <div>
                <a class="nav-link" href="{{ url_for('user1.logout')}}">退出登录</a>
            </div>
            {% else %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user1.login') }}">登录</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user1.register')}}">注册</a>
                </li>
            </ul>
            {% endif %}

        </div>
    </nav>
</div>
<div class="container">{%block body%}{%endblock%}</div>
</body>
</html>

demo5/templates/change_password.html
{% extends "base.html"%}


{% block title%} {% endblock%}


{% block head%}

{% endblock%}


{% block body%}
<div class="row" style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-8">
        <form method="POST" action="{{ url_for('user1.change_password') }}">
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">新密码</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="inputPassword" name="change_password">
                </div>
            </div>
            <div class="form-group row">
                <label for="inputPassword" class="col-sm-2 col-form-label">重新输入</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="inputPassword1" name="change_password1">
                </div>
            </div>

            {% for message in get_flashed_messages() %}
            <div class="form-group">
                <div class="text-danger">{{message}}</div>
            </div>
            {% endfor %}
            <div class="form-group" style="text-align: right;">
                <button class="btn btn-primary">修改密码</button>
            </div>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock%}

demo5/templates/core.html
{% extends "base.html"%}


{% block title%} {% endblock%}


{% block head%}

{% endblock%}


{% block body%}
<div class="row" style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-8" style="text-align:center">
        <div class="question-content">用户名：{{current_user.username}}</div>
        <div class="question-content">用户邮箱：{{current_user.email}}</div>
        <div class="question-content">注册时间：{{current_user.join_time}}</div>

    </div>
    <div class="col"></div>
</div>
{% endblock%}

demo5/templates/detail.html
{% extends "base.html"%}


{% block title%}{{ questiontitle}}{% endblock%}


{% block head%}
<link rel="stylesheet" href="{{url_for('static', filename='css/detail.css')}}">
{% endblock%}


{% block body%}
<div class="row" style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-8" style="background-color: #fff;padding: 20px;">
        <h3 class="page-title">{{question.title}}</h3>
        <P class="question-info">
            <span>作者：{{ question.author.username}}</span>
            <span>时间：{{question.create_time}}</span>
        </P>
        <hr>
        <p class="question-content">{{ question.content}}</p>
        <hr>
        <h4 class="comment-group-title">评论（{{question.answers|length}}）:</h4>
        <form action="{{ url_for('user1.answer', question_id=question.id)}}" method="post">
            <div class="form-group">
                <input type="text" placeholder="请填写评论" name="content" class="form-control">
            </div>
            {% for message in get_flashed_messages() %}
            <div class="form-group">
                <div class="text-danger">{{message}}</div>
            </div>
            {% endfor %}
            <div class="form-group" style="text-align:right;">
                <button class="btn btn-primary">评论</button>
            </div>
        </form>
        <ul class="comment-group">
            {% for answer in question.answers %}
              <li>
                <div class="user-info">
                    <img class="avatar" src="{{ url_for('static', filename='images/avater.jpg')}}">
                    <span class="username">{{answer.author.username}}</span>
                    <span class="create-time">{{answer.create_time}}</span>
                </div>
                <p class="comment-content">{{answer.content}}</p>
            </li>
            {% endfor%}

        </ul>
    </div>
    <div class="col"></div>
</div>
{% endblock%}







demo5/templates/index.html
{% extends "base.html"%}


{% block title%} 练习123 {% endblock%}


{% block head%}
<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock%}


{% block body%}
<div class="row" style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-8">
        <ul class="question-ul">
            {% for question in questions%}
            <li>
                <div class="side-question">
                    <img class="side-question-avatar" src="#" alt="">
                </div>
                <div class="question-main">
                    <div class="question-tile"><a href="{{url_for('user1.question_detail',question_id=question.id)}}">{{question.title}}</a></div>
                    <div class="question-content">{{ question.content }}</div>
                    <div class="question-detail">
                        <span class="question-author">{{question.author.username}}</span>
                        <span class="question-time">{{question.create_time}}</span>
                    </div>
                </div>
            </li>
            {% endfor%}

        </ul>
    </div>
    <div class="col"></div>
</div>
{% endblock%}







demo5/templates/login.html
{% extends "base.html"%}


{% block title%} 登录 {% endblock%}


{% block head%} {% endblock%}


{% block body%}
<div class="row mt-4">
<div class="col"></div>
<div class="col">
    <form method="post" action="{{ url_for('user1.login')}}">
  <div class="form-group">
    <label for="exampleInputEmail1">邮箱</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
    <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用户</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">密码</label>
    <input type="password" name="password" class="form-control" id="exampleInputPassword1">
  </div>

      {% for message in get_flashed_messages() %}
      <div class="form-group">
        <div class="text-danger">{{message}}</div>
      </div>
      {% endfor %}

      <div>
        <button type="submit" class="btn btn-primary btn-block">立即登录</button>
      </div>

</form>
</div>
<div class="col"></div>
    </div>

{% endblock%}







demo5/templates/public_question.html
{% extends "base.html"%}


{% block title%}{% endblock%}


{% block head%} {% endblock%}


{% block body%}
<div class="row" style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-8" style="text-align:center">
        <h1>发布问答</h1>
        <form method="post" action="{{ url_for('user1.public_question') }}">
            <div class="form-group">
                <input type="text" name="title" class="form-control" placeholder="请输入标题">
            </div>
            <div class="form-group">
                <textarea name="content" class="form-control" rows="10" placeholder="请输入内容"></textarea>
            </div>
            {% for message in get_flashed_messages() %}
            <div class="form-group">
                <div class="text-danger">{{message}}</div>
            </div>
            {% endfor %}
            <div class="form-group" style="text-align: right;">
                <button class="btn btn-primary">发布</button>
            </div>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock%}







demo5/templates/register.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html"%}


{% block title%} 注册 {% endblock%}


{% block head%}
<script src="{{ url_for('static', filename='jquery/jquery.3.6.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/register.js') }}"></script>
{% endblock%}


{% block body%}
<div class="row mt-4">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="{{ url_for('user1.register') }}">

            <div class="form-group">
                <label for="exampleInputEmail1">邮箱</label>

                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                       name="email">
                <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用户</small>
            </div>

              {% for message in get_flashed_messages() %}
            <div class="form-group">
                <div class="text-danger">{{message['email']}}</div>
            </div>
            {% endfor %}
            <div class="form-group">
                <label for="exampleInputEmail1">验证码</label>
                <div class="input-group">
                    <input type="text" class="form-control" name="captcha">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                    </div>
                </div>
            </div>
             {% for message in get_flashed_messages() %}
            <div class="form-group">
                <div class="text-danger">{{message['captcha'][1]}}</div>
            </div>
            {% endfor %}
            <div class="form-group">
                <label for="exampleInputPassword1">用户名</label>
                <input type="text" class="form-control" name="username">
            </div>
             {% for message in get_flashed_messages() %}
            <div class="form-group">
                <div class="text-danger">{{message['username']}}</div>
            </div>
            {% endfor %}
            <div class="form-group">
                <label for="exampleInputPassword1">密码</label>
                <input type="password" class="form-control" id="exampleInputPassword1" name="password">
            </div>
             {% for message in get_flashed_messages() %}
            <div class="form-group">
                <div class="text-danger">{{message['password']}}</div>
            </div>
            {% endfor %}
            <div class="form-group">
                <label for="exampleInputPassword1">确认密码</label>
                <input type="password" class="form-control" name="password_confirm">
            </div>
             {% for message in get_flashed_messages() %}
            <div class="form-group">
                <div class="text-danger">{{message['password_confirm']}}</div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary btn-block">立即注册</button>
            <!--      <input type="submit" class="btn btn-primary btn-block">-->

        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock%}





